# Generated by Django 4.1.7 on 2023-03-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2_code', models.CharField(default='QQ', max_length=3, primary_key=True, serialize=False)),
                ('alpha_3_code', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=150)),
                ('numeric_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegions',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sub_region_type', models.CharField(max_length=30)),
                ('parent_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.country')),
            ],
        ),
    ]
