# Generated by Django 4.1.7 on 2023-04-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_country_alpha_3_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEntityRemaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remap_name', models.CharField(max_length=225)),
                ('iso_country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.country')),
            ],
        ),
    ]
