services:
  dev-minio-service:

    image: minio/minio

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_storage:/data

    command: server --console-address ":9001" /data

    env_file:
      - ../common-dev.env

volumes:
  minio_storage: {}