services:
  django-app:
    build: ../../newsbycountry/
    volumes:
      - ../../newsbycountry:/code
    environment:
      - DJANGO_SETTINGS_MODULE=newsbycountry.dev_settings
    env_file:
      - common-dev.env
