# Generated by Django 4.1.7 on 2023-03-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ForeginPolicyArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('date_published', models.DateField()),
                ('link', models.URLField()),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.people')),
                ('countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.country')),
                ('page_refs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_policy.articlelinks')),
            ],
        ),
    ]
