# Generated by Django 4.1.7 on 2023-04-18 04:32

import apps.foreign_policy.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('people', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeginPolicyRssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_extracted', models.DateTimeField(auto_now_add=True)),
                ('rss_feed_xml', models.FileField(blank=True, null=True, upload_to='foreign_policy/rss_feed/%Y/%m/%d')),
                ('feed_source', models.URLField(default='https://foreignpolicy.com/feed/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeginPolicyArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('date_published', models.DateField()),
                ('link', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.foreign_policy.models.get_upload_path)),
                ('authors', models.ManyToManyField(to='people.people')),
                ('countries', models.ManyToManyField(to='geography.country')),
                ('page_refs', models.ManyToManyField(to='references.links')),
                ('rss_feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_policy.foreginpolicyrssfeed')),
                ('tags', models.ManyToManyField(to='references.tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
