# Generated by Django 4.1.7 on 2023-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='has_entity_been_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='has_entity_been_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
