# Generated by Django 3.1.4 on 2023-03-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articlelinks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
