# Generated by Django 4.1.7 on 2023-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_policy', '0002_foreginpolicyarticle_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='entry_type',
            field=models.CharField(default='Foreign Policy Magazine Article', max_length=150),
        ),
    ]
