# Generated by Django 4.1.7 on 2023-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_policy', '0004_remove_foreginpolicyarticle_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='authors_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='authors_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='authors_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='authors_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='country_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='country_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='country_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='country_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='file_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='file_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='file_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='file_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='page_refs_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='page_refs_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='page_refs_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='page_refs_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags_validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
