# Generated by Django 4.1.7 on 2023-03-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_policy', '0004_alter_foreginpolicyrssfeed_rss_feed_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeginPolicyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_policy.foreginpolicytags'),
        ),
    ]
