# Generated by Django 4.1.7 on 2023-03-14 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('geography', '0003_alter_country_id'),
        ('foreign_policy', '0005_foreginpolicytags_foreginpolicyarticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='rss_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_policy.foreginpolicyrssfeed'),
        ),
        migrations.RemoveField(
            model_name='foreginpolicyarticle',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='foreginpolicyarticle',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='foreginpolicyarticle',
            name='page_refs',
        ),
        migrations.RemoveField(
            model_name='foreginpolicyarticle',
            name='tags',
        ),
        migrations.AlterField(
            model_name='foreginpolicytags',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='authors',
            field=models.ManyToManyField(null=True, to='people.people'),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='countries',
            field=models.ManyToManyField(null=True, to='geography.country'),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='page_refs',
            field=models.ManyToManyField(null=True, to='foreign_policy.articlelinks'),
        ),
        migrations.AddField(
            model_name='foreginpolicyarticle',
            name='tags',
            field=models.ManyToManyField(null=True, to='foreign_policy.foreginpolicytags'),
        ),
    ]
