# Generated by Django 4.1.7 on 2023-03-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('geography', '0003_alter_country_id'),
        ('foreign_policy', '0006_foreginpolicyarticle_rss_feed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreginpolicyarticle',
            name='authors',
            field=models.ManyToManyField(to='people.people'),
        ),
        migrations.AlterField(
            model_name='foreginpolicyarticle',
            name='countries',
            field=models.ManyToManyField(to='geography.country'),
        ),
        migrations.AlterField(
            model_name='foreginpolicyarticle',
            name='page_refs',
            field=models.ManyToManyField(to='foreign_policy.articlelinks'),
        ),
        migrations.AlterField(
            model_name='foreginpolicyarticle',
            name='tags',
            field=models.ManyToManyField(to='foreign_policy.foreginpolicytags'),
        ),
    ]
