  services:
    rabbitmq:
      container_name: rabbitmq
      restart: always
      image: rabbitmq:3.11-management-alpine
      ports:
        - 5672:5672
        - 15672:15672      

volumes:
  rabbitmq_data:

  # When I learn more about RabbitMQ, perform configuration on the broker with a conf file. 